name: Auto Release

on:
  push:
    tags:
      - 'v*' # האוטומציה תרוץ רק כשנדחוף תגית שמתחילה באות v (כמו v1.0)

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # אישור לבוט לכתוב ולייצר Release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true # מייצר אוטומטית רשימה של מה השתנה בקוד